version: '3.8'

services:
  modelo:
    image: modelo
    build: './modelo'
    container_name: modelo
    networks:
      - aux1
    command:
      ['uvicorn', 'api_communication:app', '--host', '0.0.0.0', '--port', '80']
    ports:
      - 5000:80

  webapp:
    image: webapp
    build: './webapp'
    container_name: webapp
    ports:
      - 8787:8080
    command: 'streamlit run app.py --server.port 8080'
    networks:
      - aux1

networks:
  aux1:
    driver: bridge
